Refactor Inicial (Clean Code)
elagarrigue/AyDS23-Winchester3 pull request #10
Opened 2023-04-27 00:12 UTC by JanoALockhart

Se aplicó refactor y clean code a los archivos OtherInfoWindow y DataBase dentro del paquete othedetails.
La subcomisión conformada por Ezequiel Perez y Hernán Perez se encargaron de DataBase
La subcomisión conformada por Giuliana Guidi y Jano Lockhart se encargaron de OtherInfoWindow

2023-04-27 20:37 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +
sacar espacios entre declaraciones

2023-04-28 10:59 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        )
distintos niveles de abstraccion

2023-04-28 11:01 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (items.isEmpty()) null else items[0]
items.firstOrNull() ?: ""

2023-04-28 11:04 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(artist)
no mantiene el mismo nivel de abtraccion

2023-04-28 11:05 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun displayWindow(
ojo la identacion

2023-04-28 11:11 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                        dataBase.saveArtist(artistName, it.description)
side effects, recupera y guarda... mmmm

2023-04-28 11:13 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val textWithBold = text
definir constantes

2023-04-28 11:14 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
Distintos niveles de abstracción:

findViewById -> definir una propiedad e inicializarla
setOnClickListener
Resolver el intent y hacer el startActivity -> mover a sub funció

2023-04-28 11:17 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            displayWindow(description, artist?.wikipediaURL)
El thread debería llamar a un solo método, por cuestiones de nivel de abstracción

2023-04-28 12:08 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return getArtistFromExternalData(callResponse.body(),artistName)
dentro del return se hace muchas cosas.. traten de separar antes de retornar

2023-04-28 12:26 UTC, Luchyluz requested changes
trabajen sobre los comentarios, cualquier duda consulten..

Para poder sacar lógica de vista del algoritmo repository, la función debería retornar un objeto que contenga el string de información, url, y una bandera indicando si estaba en la db o no. Si bien en el enunciado se pide no crear nuevas clases (reestructurando la clase actual), esta nueva clase de dominio es necesaria.

2023-04-29 19:14 UTC, JanoALockhart commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(artist)
¿Para solucionarlo habría que mover la inicialización de la base de datos a una subfunción que inicialice todas las propiedades de la clase (el textView, el boton, la imagen y la base de datos), la cual sería llamada desde onCreate, por ejemplo?

2023-04-29 19:15 UTC, JanoALockhart commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                        dataBase.saveArtist(artistName, it.description)
¿habría que crear una nueva subfuncion saveArtistInfo que se llame despues de searchArtistInfo que guarde en la base de datos o no segun el flag de la data class WikipediaArtist?

2023-04-29 19:16 UTC, JanoALockhart commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return getArtistFromExternalData(callResponse.body(),artistName)
¿Se refiere a que tenemos que guardar callResponse.body() y getArtistFromExternalData en variables? ¿o hay que rehacer getArtistFromExternalData?

2023-04-29 21:08 UTC, EzeAPerez commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        )
No entendemos ah que niveles de abstracción se refiere?

2023-04-30 14:20 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        )
por un lado estas llamando a crear el cursor y por otro lado estas  devolviendo el resultado de una funcion...
la creacion del cursor deberia ser una funcion aparte...

2023-04-30 14:22 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(artist)
si, asi es como lo decis..la inicializacion de propiedades, incluso de la base de datos, es responsabilidad del oncreate.. no es responsabilidad del open..

2023-04-30 14:26 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                        dataBase.saveArtist(artistName, it.description)
exacto

2023-04-30 14:26 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return getArtistFromExternalData(callResponse.body(),artistName)
lo primero

2023-05-02 14:51 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> + private const val createArtistInfoTableQuery: String =
identacion de esta declaracion, corrijanla

2023-05-02 14:53 UTC, Luchyluz requested changes
unos detalles y listo

2023-05-03 12:56 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        while (cursor.moveToNext()) {
sacar el while

2023-05-03 12:58 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        setContentView(R.layout.activity_other_info)
moverlo a init properties

2023-05-03 13:00 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        open(intent.getStringExtra(ARTIST_NAME_EXTRA).toString())
no necesitamos el parametro, fijense en cascada

2023-05-03 13:07 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            buildArtistInfo(artistName)
revisenlo...

2023-05-03 13:07 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    e1.printStackTrace()
no impriman

2023-05-03 13:17 UTC, Luchyluz requested changes
queda poquito..

2023-05-03 13:46 UTC, giulianaguidi commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    e1.printStackTrace()
Hola luchi, si sacamos el print nos muestra un warning "Empty catch block", lo sacamos igualmente o lo dejamos?

2023-05-03 15:36 UTC, giulianaguidi commented
En el thread de openArtistInfoWindow() llamamos a showArtistInfo(), dentro de este, teníamos que dividirlo en build y display pero nos quedaban dos parámetros en las funciones así que decidimos crear la data class OtherInfoWindowUIState que almacena lo que tiene que mostrar la interfaz grafica. 
Tenemos duda con el nombre que le pusimos al método getArtistInfoFromRepository() ya que busca y guarda la información. Creemos que esta bien ya que el repositorio busca en el repositorio y lo guarda localmente en caso de que no este almacenado localmente antes.
Además, llamamos al método getArtistNameFromIntent() dentro de showArtistInfo() y no dentro de getArtistInfoFromRepository() ya que no nos parecía que sea responsabilidad del segundo. Esto es ya pensando en la próxima etapa.

2023-05-03 15:42 UTC, Luchyluz approved these changes
terminado

2023-05-03 15:43 UTC, merged