Clean mvp
elagarrigue/AyDS23-Winchester3 pull request #16
Opened 2023-05-11 01:27 UTC by hernanpow

2023-05-11 23:11 UTC, kevschweitzer requested changes
En el diagrama de clases falta representar el inyector (igual que como está en el diagrama presentado, no lo compliquen). 
Además agregar la respresentación de la BD y el servicio externo

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/presenter/ArtistDescriptionFormatter.kt
> +                (if (artist.isLocallyStored) IS_LOCALLY_STORED_PREFIX else IS_NOT_LOCALLY_STORED_PREFIX) +
IS_NOT_LOCALLY_STORED_PREFIX no es necesario. En Kotlin pueden usar un if dentro de la construcción de un string. Algo asi como ```"${if (artist.isLocallyStored) IS_LOCALLY_STORED_PREFIX} ${artistInfoToHtml(...)}"```

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/presenter/ArtistDescriptionFormatter.kt
> +        val textWithBold = text
pasar a metodo aparte

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/presenter/Presenter.kt
> +        val uiState = createUIState(artist)
UIState tiene que estar creado y se tienen que ir cambiando los datos, no crear uno nuevo cada vez. Ver como esta hecho en HomeView

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/view/MoredetailsView.kt
> +    var presenter:Presenter
Mejor que lo unico que sea visible sea el set. Sino no respecto ISP

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/view/MoredetailsView.kt
> +        val artistName = getArtistNameFromIntent()
usar mismo nivel de abstracción. Pasar a un metodo aparte el seteo

2023-05-11 23:11 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/view/MoredetailsView.kt
> +        setContentView(R.layout.activity_other_info)
Esto tiene que estar en el onCreate en la segunda linea

2023-05-15 17:13 UTC, EzeAPerez commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/data/externalWikipedia/service/WikipediaServiceImpl.kt
> +        artistInfo?.name = artistName
Para solucionar esto pensaba dos opciones, pasarle por parámetros el string artistName a la funcion getArtistFromExternalData y lo setearia de esta forma:
 WikipediaArtist(name=artistName, description=query.getDescription(), wikipediaURL=query.getWikipediaUrl())
O la otra opción es que en la clase WikipediaToArtistsResolverImpl crear una nueva función que obtenga el titulo del articulo de la api, que supuestamente va a ser el nombre del artista: 
WikipediaArtist(name=query.getArtistName(), description=query.getDescription(), wikipediaURL=query.getWikipediaUrl())
private fun JsonObject.getArtistName() = this["title"].asString

2023-05-15 17:26 UTC, JanoALockhart commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/presenter/ArtistDescriptionFormatter.kt
> +                (if (artist.isLocallyStored) IS_LOCALLY_STORED_PREFIX else IS_NOT_LOCALLY_STORED_PREFIX) +
Buenas tardes. Intentamos cambiarlo a como está en el ejemplo, pero nos muestra un error que dice que si el if se usa como expresión, tiene que tener si o si el else. Luego, en el ${artistInfoToHtml(...)} muestra un warning que dice que el string template es redundante. ¿Cómo procedemos?

2023-05-15 17:46 UTC, JanoALockhart commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/view/MoredetailsView.kt
> +        val artistName = getArtistNameFromIntent()
Para solucionar esto ¿habría que colocar getArtistNameFromIntent() y openArtistInfoWindow() en un método aparte? ¿o tener una propiedad artistName en la view y que getArtistNameFromIntent inicialice esa propiedad?

2023-05-17 13:10 UTC, kevschweitzer requested changes
Diagrama de clases:
-  Fijense que en presentation tienen flechas entre interfaces. Esto no es asi. Quien conoce a presenter es MoreDetailsViewImpl, no la interfaz. Lo mismo con presenter y el Formatter

- No le cambien el nombre a la activity

2023-05-17 13:10 UTC, kevschweitzer commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/presentation/view/MoredetailsView.kt
> +        Thread {
Crear el thread en el presenter

2023-05-17 14:17 UTC, kevschweitzer approved these changes

2023-05-17 14:18 UTC, merged